### ISSUE TITLE
src 数据源用http请求

### ISSUE THREAD

**Issue by wanmeishijie12** [xuchangjunjx/asciinema-player-vue#1]
大神您好！您写的教程太棒了，解决了我的问题，单我想用src用http://XXX.cast,怎么操作？您的只能用本地的录像文件啊，我们的都放在服务器上了，总不能一个一个下载到本地再执行吧。能解决一下不，谢谢了。

**Comment by xuchangjunjx** [comment]
@wanmeishijie12 修改下，现在可以了。和普通调用API一样，example也更新了下。

**Comment by wanmeishijie12** [comment]
我试了啊，本地就不行，看截图。下载下来，就改了一下路径：  data: "./record.cast",    然后，浏览器就报错：Uncaught only asciicast v1 and v2 formats can be opened


![error2](https://user-images.githubusercontent.com/78674014/107140341-3e6a6580-695c-11eb-9db4-38e45982c07c.png)
![error1](https://user-images.githubusercontent.com/78674014/107140344-41fdec80-695c-11eb-8710-e8a830bed4d6.png)

**Comment by wanmeishijie12** [comment]
您好！大神，远程的可以调用了。谢谢了，但是，点击第一个回放之后，正常播放，关闭以后，并没有销毁，点击第二个回放的时候，src变了，但是加载的还是第一个回放。是不是有一个销毁函数，关闭以后，把第一个销毁，点击第二个回放，可以重新加载呢，而不是每次都要刷新网页。

**Comment by xuchangjunjx** [comment]
@wanmeishijie12 😢 改好了 我这写完第一版还没使用上 ，所以没怎么仔细测。

**Comment by wanmeishijie12** [comment]
谢谢。弄好了。
