### ISSUE TITLE
asciinema-player.js:981 Uncaught only asciicast v1 and v2 formats can be opened

### ISSUE THREAD

**Issue by liminghua999** [xuchangjunjx/asciinema-player-vue#2]
`Do U meet this error when run your example:`

`asciinema-player.js:981 Uncaught only asciicast v1 and v2 formats can be opened`

**Comment by xuchangjunjx** [comment]
@liminghua999 
It's my problem.
Now, I have complete the `App.vue ` & `vue.config.js`
* config proxy to load cast file from third service
* config raw-loader to load local cast file

**Comment by xuchangjunjx** [comment]
@liminghua999 
It's my problem.
Now, I have perfect the `App.vue ` & `vue.config.js`
* config proxy to load cast file from third service
* config raw-loader to load local cast file 

try~
